extends:
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:unicorn/recommended'
  - 'plugin:@typescript-eslint/stylistic'
  - 'airbnb-typescript/base'
  - 'plugin:prettier/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'
plugins:
  - 'import'
  - '@typescript-eslint'
  - 'unicorn'
root: true
rules:
  import/extensions: 'off'
  unicorn/prefer-module: 'off'
  unicorn/prevent-abbreviations: 'off'
  max-len:
    - 'error'
    - code: 80
      tabWidth: 2
      ignoreStrings: true
      ignoreComments: true
  object-curly-spacing:
    - 'error'
    - 'always'
  '@typescript-eslint/naming-convention':
    - 'error'
    - {
        selector: 'variableLike',
        format: ['camelCase'],
        leadingUnderscore: 'allow',
      }
  '@typescript-eslint/no-explicit-any': 'off'
  '@typescript-eslint/object-curly-spacing':
    - 'error'
    - 'always'
  '@typescript-eslint/consistent-type-definitions':
    - 'error'
    - 'interface'
  no-unused-vars': 'off'
  '@typescript-eslint/no-unused-vars':
    - 'error'
    - argsIgnorePattern: '_'
